# Generated by Django 6.0.4 on 2026-05-18 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('banner_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='venues.venue')),
            ],
            options={
                'db_table': 'concerts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConcertArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_concerts', to='artists.artist')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_artists', to='concerts.concert')),
            ],
            options={
                'db_table': 'concert_artists',
                'unique_together': {('concert', 'artist')},
            },
        ),
    ]
